export const GET_CATEGORIES = 'GET_CATEGORIES';
export const CREATE_CATEGORIES = 'CREATE_CATEGORIES';
export const GET_PRODUCTS = 'GET_PRODUCTS';
export const CREATE_PRODUCTS = 'CREATE_PRODUCTS';
export const REMOVE_PRODUCTS = 'REMOVE_PRODUCTS';
export const EDIT_PRODUCTS = 'EDIT_PRODUCTS';
